package Semantic.AccionesSemanticas;

public enum AccionSemantica {
    INSERTAR_TS, RECUERDA_ID,RECUERDA_TIPO, RECUERDA_OP , EVAL_BINARY, RECUERDA_VARIABLE,
    START_IF, START_ELSE, END_IF, TEST_IF,
    START_WHILE, TEST_WHILE, END_WHILE

}
