package CompiladorC;

import java_cup.runtime.*;

class Parser;

/*Terminales*/

terminal PLUS, TIMES, LPAREN, RPAREN;
terminal Integer NUMBER;

/*No Terminales*/

non terminal Integer expr;

/*Presedencia*/

precedence left PLUS;
precedence left TIMES;

/*Gramáticas*/

start with expr;

expr ::= expr:e1 PLUS expr:e2 {: RESULT = e1 + e2; :}
      |  expr:e1 TIMES expr:e2 {: RESULT = e1 * e2; :}
      |  LPAREN expr:e RPAREN  {: RESULT = e; :}
      |  NUMBER:n              {: RESULT = n; :};